#!/bin/bash

# Script de déploiement sur Render.com
# Usage: ./deploy-render.sh

echo "🚀 DÉPLOIEMENT GRATUIT SUR RENDER.COM"
echo "===================================="

echo ""
echo "📋 PRÉREQUIS :"
echo "✅ Compte GitHub créé"
echo "✅ Dépôt medical-erp créé"
echo "✅ Compte Render.com créé"
echo ""

echo "🛠️ ÉTAPES DE DÉPLOIEMENT :"
echo ""
echo "1️⃣  Préparation du projet :"
echo "   git add ."
echo "   git commit -m 'Deploy Medical ERP'"
echo "   git push origin main"
echo ""
echo "2️⃣  Configuration Render :"
echo "   - Allez sur https://render.com"
echo "   - Connectez-vous avec GitHub"
echo "   - New Web Service"
echo "   - Sélectionnez votre dépôt medical-erp"
echo "   - Runtime : Docker"
echo "   - Plan : Free"
echo ""
echo "3️⃣  Configuration base de données :"
echo "   - New PostgreSQL"
echo "   - Nom : medical-db"
echo "   - Plan : Free"
echo "   - Copiez les identifiants"
echo ""
echo "4️⃣  Variables d'environnement :"
echo "   - HOST=medical-db"
echo "   - PORT=8069"
echo "   - USER=odoo"
echo "   - PASSWORD=votre_password"
echo "   - DB_NAME=medical_db"
echo ""
echo "5️⃣  Déploiement automatique :"
echo "   - Render déploie automatiquement"
echo "   - Attendez 5-10 minutes"
echo "   - Votre URL sera disponible"
echo ""
echo "🌟 AVANTAGES DE RENDER.COM :"
echo "✅ 750 heures/mois gratuites"
echo "✅ Base de données PostgreSQL gratuite"
echo "✅ HTTPS automatique"
echo "✅ Déploiement automatique"
echo "✅ Domaine personnalisé"
echo "✅ Monitoring inclus"
echo ""
echo "🎯 URL FINALE :"
echo "https://medical-erp.onrender.com"
echo ""
echo "📱 POUR LA PRÉSENTATION :"
echo "✅ Accessible sur mobile"
echo "✅ URL professionnelle"
echo "✅ HTTPS sécurisé"
echo "✅ Fonctionnalités complètes"
echo ""
echo "⏰ TEMPS DE DÉPLOIEMENT : 5-15 minutes"
echo "🎉 VOTRE PROJET SERA EN LIGNE !"
echo ""
echo "💡 CONSEILS :"
echo "• Testez bien avant la présentation"
echo "• Vérifiez que toutes les fonctionnalités marchent"
echo "• Gardez l'URL pour la partager avec le jury"
echo ""
echo "🚀 LANCEZ MAINTENANT :"
echo "👉 https://render.com"
