#!/bin/bash

# Script de préparation manuelle pour Render
# Usage: ./prepare-render.sh

echo "📦 PRÉPARATION MANUELLE POUR RENDER"
echo "=================================="

echo ""
echo "📋 ÉTAPES SANS GIT :"
echo ""
echo "1️⃣  Créez un compte GitHub :"
echo "   👉 https://github.com/signup"
echo ""
echo "2️⃣  Créez un nouveau dépôt :"
echo "   - Nom : medical-erp"
echo "   - Description : Module Médical ERP pour Odoo 16"
echo "   - Public : Oui"
echo ""
echo "3️⃣  Préparez votre projet localement :"
echo "   - Créez un dossier ZIP avec tout votre projet"
echo "   - Nommez-le : medical-erp.zip"
echo ""
echo "4️⃣  Uploadez sur GitHub :"
echo "   - Allez sur votre dépôt GitHub"
echo "   - Cliquez sur 'Add file' → 'Upload files'"
echo "   - Uploadez tous vos fichiers"
echo ""
echo "5️⃣  Configurez Render :"
echo "   👉 https://render.com"
echo "   - Créez un compte avec GitHub"
echo "   - New Web Service"
echo "   - Connectez votre dépôt medical-erp"
echo ""
echo "📁 FICHIERS NÉCESSAIRES :"
echo "✅ Dockerfile"
echo "✅ render.yaml"
echo "✅ addons/ (tout le dossier)"
echo "✅ docker-compose.yml"
echo "✅ requirements.txt (si vous en avez un)"
echo ""
echo "🎯 URL FINALE :"
echo "https://medical-erp.onrender.com"
echo ""
echo "⏰ TEMPS DE PRÉPARATION : 15-20 minutes"
echo "🎉 VOTRE PROJET SERA DÉPLOYÉ !"
echo ""
echo "💡 CONSEILS :"
echo "• Vérifiez que tous les fichiers sont uploadés"
echo "• Testez la configuration Docker localement"
echo "• Gardez votre URL pour la présentation"
