services:
  # Service PostgreSQL
  - type: pserv
    name: medical-db
    env: docker
    repo: https://github.com/Tayga1234/projet_erp.git
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: medical_db
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        value: odoo123

  # Service Odoo
  - type: web
    name: medical-erp
    env: docker
    repo: https://github.com/Tayga1234/projet_erp.git
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: HOST
        value: medical-db
      - key: PORT
        value: 8069
      - key: USER
        value: odoo
      - key: PASSWORD
        value: odoo123
      - key: DB_NAME
        value: medical_db
    healthCheckPath: /web
    domains:
      - medical-erp.onrender.com
